-- 13. ACTUALIZAR TABLA VENTAS CON CLIENTE, FINCA Y TIPO DE PAGO
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS cliente_id UUID REFERENCES clientes(id) ON DELETE SET NULL;
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS finca_id UUID REFERENCES fincas(id) ON DELETE SET NULL;
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS tipo_pago TEXT DEFAULT 'EFECTIVO';
